# syntax=docker/dockerfile:1
#
# citrate-bundler — packages eth-infinitism's reference ERC-4337 v0.7
# bundler (Apache 2.0) into a runnable Citrate-flavoured image.
#
# v0.7-aligned bundler is shipped via the upstream account-abstraction
# monorepo (https://github.com/eth-infinitism/bundler). We pin to a specific
# COMMIT SHA (not the moving `releases/v0.7` branch head) and fetch that exact
# object, so an upstream branch advance / force-push can never silently change
# our binary. `scripts/check-image-pins.mjs` (BUN-B-004 tripwire) fails CI if
# BUNDLER_REF is ever set back to a branch/tag name.
#
# Multi-stage:
#  1. builder — clone upstream + yarn install + tsc → dist/
#  2. runtime — node:22-alpine + dist + production deps only

ARG BUNDLER_REPO=https://github.com/eth-infinitism/bundler.git
# Pinned to the tip of releases/v0.7 as of 2026-09-06
# (git ls-remote eth-infinitism/bundler releases/v0.7). Bump this SHA
# deliberately in a reviewed PR to take a newer upstream fix.
ARG BUNDLER_REF=1868538f1d7678576291d2ecabb4443c797ad133

# ---- 1. builder ----
FROM node:22-alpine AS builder
WORKDIR /build
# node-gyp (native deps like @parcel/watcher, needed on arm64/musl where no
# prebuilt ships) requires Python with `distutils`. Alpine's python3 is now 3.12,
# which REMOVED distutils — `py3-setuptools` restores the shim so node-gyp's
# configure step works. `linux-headers` provides the system headers the native
# compile needs. (Without these the build dies at `yarn install` with
# `ModuleNotFoundError: No module named 'distutils'`.)
RUN apk add --no-cache git python3 py3-setuptools make g++ linux-headers

# Fetch the upstream bundler at the pinned COMMIT SHA. `git clone --branch`
# only accepts a branch/tag name, so to pin to a SHA we init + fetch the exact
# object (GitHub serves reachable commit SHAs). Submodules are pulled AFTER
# checkout because the `account-abstraction` contracts submodule + its prepack
# output are consumed by the bundler workspace at typecheck time.
ARG BUNDLER_REPO
ARG BUNDLER_REF
RUN git init bundler \
 && cd bundler \
 && git remote add origin ${BUNDLER_REPO} \
 && git fetch --depth 1 origin ${BUNDLER_REF} \
 && git checkout --detach FETCH_HEAD \
 && git submodule update --init --recursive --depth 1

WORKDIR /build/bundler
# Upstream uses bash in its prepack/postpack scripts; alpine ships sh-only.
RUN apk add --no-cache bash
# Yarn is the upstream's package manager.
RUN corepack enable && corepack prepare yarn@stable --activate
# Install workspace deps with lockfile integrity ENFORCED. We pin to an exact
# upstream SHA above, so `yarn.lock` at that commit is authoritative; a
# `--immutable` failure means the dependency graph does not match the pinned
# lockfile — the exact signal of a supply-chain substitution — and MUST be
# fatal, not silently retried without integrity enforcement (BUN-B-004).
RUN yarn install --immutable
# Upstream's `preprocess` is the canonical "go-from-fresh-clone-to-
# typechecked-monorepo" step. It does:
#   1. submodule-update (no-op for us, already recursed at clone)
#   2. yarn install at the root + at submodules/account-abstraction
#   3. yarn --cwd contracts prepack (generates the @account-abstraction/
#      contracts artifacts the bundler imports)
#   4. hardhat-compile across all workspaces (best-effort; some example
#      packages have stale solidity we don't ship — yarn returns non-zero
#      on first hardhat error, so wrap in `|| true`)
#   5. lerna-tsc — compiles every @account-abstraction/* workspace in
#      dependency order. The bundler workspace's TS imports
#      (`@account-abstraction/utils`, `@account-abstraction/sdk`,
#      `@account-abstraction/validation-manager`) come from sibling
#      workspaces and need those compiled first.
# Step 1: install + hardhat-compile the contracts submodule. The
# `@account-abstraction/utils` workspace at root imports
# `@account-abstraction/contracts/artifacts/IEntryPoint.json` (and
# friends) — those .json files are GENERATED by hardhat compiling
# the contracts package, and they must exist on disk before
# lerna-tsc tries to typecheck the workspace tree.
#
# Why `yarn hardhat compile` and not `yarn compile`: the contracts
# submodule's package.json (releases/v0.7 ref) defines only `prepack`
# / `postpack` scripts — there's no `compile` alias. We call hardhat
# directly via the local node_modules' binary, matching what
# `scripts/prepack-contracts-package.sh` does internally.
# The hardhat.config.ts lives at submodules/account-abstraction/ root
# (one level above the contracts/ package) and pulls in
# @nomiclabs/hardhat-waffle + sibling plugins listed in that level's
# package.json. Install + compile at THAT level, not inside contracts/.
RUN cd submodules/account-abstraction && yarn install --immutable
RUN cd submodules/account-abstraction && yarn hardhat compile
# Step 2: prepack — copies the compiled artifacts into the package's
# published layout so the workspace symlinks resolve to populated
# artifact JSON.
RUN cd submodules/account-abstraction && bash scripts/prepack-contracts-package.sh
# Step 3: hardhat-compile at the bundler root (best-effort; some
# example packages have stale solidity we don't ship — yarn returns
# non-zero on first hardhat error, so wrap in `|| true`).
RUN yarn hardhat-compile || true
# Step 4: compile every workspace TS in dependency order. With the
# contracts artifacts populated and prepacked above, @account-abstraction/
# utils + sdk + validation-manager + bundler all typecheck.
RUN yarn lerna-tsc

# ---- 2. runtime ----
FROM node:22-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app

# Run as the unprivileged `node` user (uid/gid 1000) the base image ships.
COPY --from=builder --chown=node:node /build/bundler /app

# Entrypoint script (scripts/citrate-bundler-entrypoint.sh) — templates the
# upstream's localconfig/bundler.config.json + mnemonic.txt from our compose
# env vars, enforces the BUN-B-001 boot guard (refuses --unsafe on an
# anonymous RPC front door), then execs the real bundler. Kept as a real file
# (not an inline heredoc) so the boot guard + generated config floors are
# testable without a Docker build. The upstream bundler reads its config from
# disk (the only injection point is `--config <path>`); we write the file at
# boot rather than baking it in so secrets stay out of the image.
USER root
COPY --chown=root:root scripts/citrate-bundler-entrypoint.sh /usr/local/bin/citrate-bundler-entrypoint.sh
# BUN-B-010: the entrypoint runs as root only long enough to template the
# config + drop privilege via busybox `su`; it must fail loudly if it cannot be
# made executable. The previous `&& apk add --no-cache su-exec || true`
# installed a tool the script never uses AND the `|| true` masked a failed
# chmod — both removed.
RUN chmod 0755 /usr/local/bin/citrate-bundler-entrypoint.sh

EXPOSE 3000

# Liveness probe — JSON-RPC eth_chainId smoke test against the bundler's
# HTTP listener. Returns 200 + a JSON-RPC envelope when the upstream is
# accepting requests, even before any UserOps land.
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/rpc', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', method: 'eth_chainId', id: 1 }) }).then(r => process.exit(r.status === 200 ? 0 : 1)).catch(() => process.exit(1))"

ENTRYPOINT ["/usr/local/bin/citrate-bundler-entrypoint.sh"]
CMD []
