# syntax=docker/dockerfile:1
#
# citrate-bundler — packages eth-infinitism's reference ERC-4337 v0.7
# bundler (Apache 2.0) into a runnable Citrate-flavoured image.
#
# v0.7-aligned bundler is shipped via the upstream account-abstraction
# monorepo (https://github.com/eth-infinitism/bundler) at the
# `releases/v0.7` branch. We pin to a specific commit via build arg
# so an upstream main-branch shift never silently changes our binary.
#
# Multi-stage:
#  1. builder — clone upstream + yarn install + tsc → dist/
#  2. runtime — node:22-alpine + dist + production deps only

ARG BUNDLER_REPO=https://github.com/eth-infinitism/bundler.git
# v0.7-tagged release. Override at build time with --build-arg if a
# newer fix lands and we want to take it.
ARG BUNDLER_REF=releases/v0.7

# ---- 1. builder ----
FROM node:22-alpine AS builder
WORKDIR /build
RUN apk add --no-cache git python3 make g++

# Clone the upstream bundler at the pinned ref. `--recurse-submodules`
# is REQUIRED because upstream pulls the `account-abstraction` contracts
# repo in as a submodule + its prepack output is consumed by the
# bundler workspace at typecheck time.
ARG BUNDLER_REPO
ARG BUNDLER_REF
RUN git clone --depth 1 --branch ${BUNDLER_REF} --recurse-submodules --shallow-submodules ${BUNDLER_REPO} bundler

WORKDIR /build/bundler
# Upstream uses bash in its prepack/postpack scripts; alpine ships sh-only.
RUN apk add --no-cache bash
# Yarn is the upstream's package manager.
RUN corepack enable && corepack prepare yarn@stable --activate
# Install workspace deps. `--immutable` then a permissive retry in case
# the lockfile drifted between releases/v0.7 and a transient dep.
RUN yarn install --immutable || yarn install
# Upstream's `preprocess` is the canonical "go-from-fresh-clone-to-
# typechecked-monorepo" step. It does:
#   1. submodule-update (no-op for us, already recursed at clone)
#   2. yarn install at the root + at submodules/account-abstraction
#   3. yarn --cwd contracts prepack (generates the @account-abstraction/
#      contracts artifacts the bundler imports)
#   4. hardhat-compile across all workspaces (best-effort; some example
#      packages have stale solidity we don't ship — yarn returns non-zero
#      on first hardhat error, so wrap in `|| true`)
#   5. lerna-tsc — compiles every @account-abstraction/* workspace in
#      dependency order. The bundler workspace's TS imports
#      (`@account-abstraction/utils`, `@account-abstraction/sdk`,
#      `@account-abstraction/validation-manager`) come from sibling
#      workspaces and need those compiled first.
# Step 1: install + hardhat-compile the contracts submodule. The
# `@account-abstraction/utils` workspace at root imports
# `@account-abstraction/contracts/artifacts/IEntryPoint.json` (and
# friends) — those .json files are GENERATED by hardhat compiling
# the contracts package, and they must exist on disk before
# lerna-tsc tries to typecheck the workspace tree.
#
# Why `yarn hardhat compile` and not `yarn compile`: the contracts
# submodule's package.json (releases/v0.7 ref) defines only `prepack`
# / `postpack` scripts — there's no `compile` alias. We call hardhat
# directly via the local node_modules' binary, matching what
# `scripts/prepack-contracts-package.sh` does internally.
# The hardhat.config.ts lives at submodules/account-abstraction/ root
# (one level above the contracts/ package) and pulls in
# @nomiclabs/hardhat-waffle + sibling plugins listed in that level's
# package.json. Install + compile at THAT level, not inside contracts/.
RUN cd submodules/account-abstraction && yarn install --immutable
RUN cd submodules/account-abstraction && yarn hardhat compile
# Step 2: prepack — copies the compiled artifacts into the package's
# published layout so the workspace symlinks resolve to populated
# artifact JSON.
RUN cd submodules/account-abstraction && bash scripts/prepack-contracts-package.sh
# Step 3: hardhat-compile at the bundler root (best-effort; some
# example packages have stale solidity we don't ship — yarn returns
# non-zero on first hardhat error, so wrap in `|| true`).
RUN yarn hardhat-compile || true
# Step 4: compile every workspace TS in dependency order. With the
# contracts artifacts populated and prepacked above, @account-abstraction/
# utils + sdk + validation-manager + bundler all typecheck.
RUN yarn lerna-tsc

# ---- 2. runtime ----
FROM node:22-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app

# Run as the unprivileged `node` user (uid/gid 1000) the base image ships.
COPY --from=builder --chown=node:node /build/bundler /app

# Entrypoint script — templates the upstream's localconfig/bundler.config.json
# + mnemonic.txt from our compose env vars before invoking the real bundler.
# The upstream bundler reads its config from disk (the only injection point
# is `--config <path>`); we write the file at boot rather than baking it in
# so secrets stay out of the image.
USER root
COPY --chown=root:root <<'ENTRYPOINT_EOF' /usr/local/bin/citrate-bundler-entrypoint.sh
#!/bin/sh
set -eu

: "${MNEMONIC:?MNEMONIC env required (12-word BIP-39)}"
: "${NETWORK:?NETWORK env required (chain JSON-RPC URL)}"
: "${ENTRYPOINT:?ENTRYPOINT env required (chain EntryPoint address)}"
: "${PORT:=3000}"
: "${BENEFICIARY:=}"
: "${AUTO_BUNDLE_INTERVAL:=3}"

CFG_DIR=/app/packages/bundler/localconfig
mkdir -p "${CFG_DIR}"

printf '%s\n' "${MNEMONIC}" > "${CFG_DIR}/mnemonic.txt"
chmod 0600 "${CFG_DIR}/mnemonic.txt"

# If no beneficiary supplied, the bundler defaults to the operator EOA.
# Leave the field as an empty string to trigger that.
cat > "${CFG_DIR}/bundler.config.json" <<JSON
{
  "gasFactor": "1",
  "port": "${PORT}",
  "network": "${NETWORK}",
  "entryPoint": "${ENTRYPOINT}",
  "beneficiary": "${BENEFICIARY}",
  "minBalance": "1",
  "mnemonic": "./localconfig/mnemonic.txt",
  "maxBundleGas": 5000000,
  "minStake": "1",
  "minUnstakeDelay": 0,
  "autoBundleInterval": ${AUTO_BUNDLE_INTERVAL},
  "autoBundleMempoolSize": 10
}
JSON

cd /app/packages/bundler
# `--unsafe` skips the bundler's debug_traceCall full-validation step.
# Citrate chain RPC doesn't expose debug_traceCall (it's a Geth/Erigon-only
# trace method); for our single-tenant deployment (all UserOps originate
# from auth.citrate.ai's verified clients, not a public mempool) the
# unsafe-mode signature + nonce + paymaster validation is sufficient.
# When the chain gains debug_traceCall, drop `--unsafe`.
#
# `--auto` enables the autobundling loop (otherwise the bundler accepts
# UserOps but never submits batches; the upstream README treats `--auto`
# as the production default).
#
# Drop privileges to `node` for the runtime.
exec su -s /bin/sh node -c "node dist/src/exec.js --config ${CFG_DIR}/bundler.config.json --unsafe --auto"
ENTRYPOINT_EOF
RUN chmod 0755 /usr/local/bin/citrate-bundler-entrypoint.sh && apk add --no-cache su-exec || true

EXPOSE 3000

# Liveness probe — JSON-RPC eth_chainId smoke test against the bundler's
# HTTP listener. Returns 200 + a JSON-RPC envelope when the upstream is
# accepting requests, even before any UserOps land.
HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/rpc', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', method: 'eth_chainId', id: 1 }) }).then(r => process.exit(r.status === 200 ? 0 : 1)).catch(() => process.exit(1))"

ENTRYPOINT ["/usr/local/bin/citrate-bundler-entrypoint.sh"]
CMD []
